#pragma once

#ifdef POINTING_DEVICE_ENABLE
  #define SPLIT_POINTING_ENABLE
  #define POINTING_DEVICE_COMBINED
  
  #define POINTING_DEVICE_ROTATION_180//左手スクロール・右手カーソルの場合は_RIGHTを末尾に追加
  #define POINTING_DEVICE_INVERT_X
  #define POINTING_DEVICE_INVERT_X_RIGHT
  #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
  #define AUTO_MOUSE_DEFAULT_LAYER 3
  #define AUTO_MOUSE_TIME 650
#endif