ENCODER_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_SPLITS += yes
POINTING_DEVICE_DRIVER = custom
SRC += iqs5xx.c i2c_master.c qmk_rc.c

SPLIT_KEYBOARD_ENABLE = yes

MOUSEKEY_ENABLE = yes  